### ISSUE TITLE
hxcpp garbage collector leaks memory

### ISSUE THREAD

**Issue by bjitivo** [HaxeFoundation/hxcpp#315]
Here is a test program that I wrote a long time ago to stress test the hxcpp garbage collector:

```
/** *************************************************************************
 * StressGC.hx
 *
 * Copyright 2013 TiVo, Inc.
 ************************************************************************** **/

class StressGC
{
    public static function main()
    {
        var argv = Sys.args();

        var maxArrays = 2000;
        var maxStrings = 2000;
        var maxObjects = 2000;
        var clear_after = 10000;
        var iterations = -1;
        var thread_count = 1;

        var seed : Int = 0;
        var seeded = false;

        var iter = 0 ... argv.length;
        for (i in iter) {
            var arg = argv[i];
            switch (arg) {
            case "-s":
                if (i == (argv.length - 1)) {
                    Sys.stderr().writeString
                        ("ERROR: -s requires an argument\n");
                    Sys.exit(-1);
                }
                seed = Std.parseInt(argv[i + 1]);
                i = iter.next();
                seeded = true;

            case "-i":
                if (i == (argv.length - 1)) {
                    Sys.stderr().writeString
                        ("ERROR: -i requires an argument\n");
                    Sys.exit(-1);
                }
                iterations = Std.parseInt(argv[i + 1]);
                i = iter.next();
                
            case "-c":
                if (i == (argv.length - 1)) {
                    Sys.stderr().writeString
                        ("ERROR: -c requires an argument\n");
                    Sys.exit(-1);
                }
                clear_after = Std.parseInt(argv[i + 1]);
                if (clear_after < 0) {
                    Sys.stderr().writeString("ERROR: -c requires an " +
                                             "argument >= 0\n");
                    Sys.exit(-1);
                }
                i = iter.next();

            case "-am":
                if (i == (argv.length - 1)) {
                    Sys.stderr().writeString
                        ("ERROR: -am requires an argument\n");
                    Sys.exit(-1);
                }
                maxArrays = Std.parseInt(argv[i + 1]);
                if (maxArrays < 0) {
                    Sys.stderr().writeString
                        ("ERROR: -am requires an argument > 0\n");
                    Sys.exit(-1);
                }
                i = iter.next();

            case "-sm":
                if (i == (argv.length - 1)) {
                    Sys.stderr().writeString
                        ("ERROR: -sm requires an argument\n");
                    Sys.exit(-1);
                }
                maxStrings = Std.parseInt(argv[i + 1]);
                if (maxStrings < 0) {
                    Sys.stderr().writeString
                        ("ERROR: -sm requires an argument > 0\n");
                    Sys.exit(-1);
                }
                i = iter.next();

            case "-om":
                if (i == (argv.length - 1)) {
                    Sys.stderr().writeString
                        ("ERROR: -om requires an argument\n");
                    Sys.exit(-1);
                }
                maxObjects = Std.parseInt(argv[i + 1]);
                if (maxObjects < 0) {
                    Sys.stderr().writeString
                        ("ERROR: -om requires an argument > 0\n");
                    Sys.exit(-1);
                }
                i = iter.next();

            case "-tc":
                if (i == (argv.length - 1)) {
                    Sys.stderr().writeString
                        ("ERROR: -tc requires an argument\n");
                    Sys.exit(-1);
                }
                thread_count = Std.parseInt(argv[i + 1]);
                if (thread_count < 1) {
                    Sys.stderr().writeString
                        ("ERROR: -tc requires an argument > 0\n");
                    Sys.exit(-1);
                }
                i = iter.next();

            default:
                Sys.stderr().writeString
                    ("ERROR: unknown argumnt: " + arg + "\n");
                Sys.exit(-1);
            }
        }

        if ((maxArrays == 0) && (maxStrings == 0) && (maxObjects == 0)) {
            Sys.stderr().writeString("ERROR: At least one of -am, -sm or -om " +
                                     "must have an argument > 0\n");
            Sys.exit(-1);
        }

        Runner.setMaxArrays(maxArrays);
        Runner.setMaxStrings(maxStrings);
        Runner.setMaxObjects(maxObjects);
        Runner.setClearAfter(clear_after);

        if (!seeded) {
            seed = Std.int(Sys.time() * 100);
        }

        Sys.println("Using random seed: " + seed);

        // Create the Runners
        var arr = new Array<Runner>();
        for (i in 0 ... thread_count) {
            arr.push(new Runner(i, iterations, seed + i));
        }

        // Start the Runners
        for (i in 0 ... arr.length) {
            arr[i].start();
        }

        // Wait for all to be done
        for (i in 0 ... arr.length) {
            arr[i].join();
        }

#if cpp
        cpp.vm.Gc.run(true);
#elseif neko
        neko.vm.Gc.run(true);
#end

        return 0;
    }
}


class Runner
{
    public static function setMaxArrays(max : Int)
    {
        gMaxArrays = max;
    }

    public static function setMaxStrings(max : Int)
    {
        gMaxStrings = max;
    }

    public static function setMaxObjects(max : Int)
    {
        gMaxObjects = max;
    }

    public static function setClearAfter(clear_after : Int)
    {
        gClearAfter = clear_after;
    }

    public function new(num : Int, iters : Int, seed : Int)
    {
        mNum = num;
        mIters = iters;
        mRandom = new Random(seed);
        mObject = new Object(mRandom, gMaxArrays, gMaxStrings, gMaxObjects);
#if cpp
        mJoinQ = new cpp.vm.Deque<Int>();
        mThread = cpp.vm.Thread.create(thread_main);
#elseif neko
        mJoinQ = new neko.vm.Deque<Int>();
        mThread = neko.vm.Thread.create(thread_main);
#end
    }

    public function start()
    {
#if (cpp || neko)
        // Send the runner to the thread to start it
        mThread.sendMessage(this);
#else
        this.run();
#end
    }

    public function join()
    {
#if (cpp || neko)
        // Read the message send at the end of run()
        mJoinQ.pop(true);
#end
    }

    private function run()
    {
        var iter_num = 0;

        while ((mIters == -1) || (--mIters > 0)) {
            iter_num += 1;
            mObject.iterate();
            
            if ((iter_num % 1000) == 0) {
                mObject.dump("" + mNum + " @ " + iter_num + ": ");
            }

            if ((gClearAfter > 0) && ((iter_num % gClearAfter) == 0)) {
                mObject.clear("" + mNum + " @ " + iter_num + ": ");
            }
        }
        
        mObject.clear("" + mNum + " @ " + iter_num + ": ");
    }

#if (cpp || neko)
    private static function thread_main()
    {
        // Wait for start() to send the Runner
        var runner : Runner = cpp.vm.Thread.readMessage(true);

        // Run the runner
        runner.run();

        // Send a message which join() will read
        runner.mJoinQ.push(0);
    }
#end

    static private var gMaxArrays : Int;
    static private var gMaxStrings : Int;
    static private var gMaxObjects : Int;
    private static var gClearAfter : Int;

    private var mNum : Int;
    private var mIters : Int;
    private var mRandom : Random;
    private var mObject : Object;

#if cpp
    private var mJoinQ : cpp.vm.Deque<Int>;
    private var mThread : cpp.vm.Thread;
#elseif neko
    private var mJoinQ : neko.vm.Deque<Int>;
    private var mThread : neko.vm.Thread;
#end
}


class Object
{
    public function new(random : Random, maxArrays : Int, maxStrings : Int,
                        maxObjects : Int)
    {
        mRandom = random;
        mMaxArrays = maxArrays;
        mMaxStrings = maxStrings;
        mMaxObjects = maxObjects;
        this.allocate();
    }

    public function iterate()
    {
        if (mIterators.length > 0) {
            mIterators[mRandom.random() % mIterators.length]();
        }
    }

    public function clear(prefix : String)
    {
        var clear_count : Int = 0;
        if (mObjects != null) {
            for (i in 0 ... mObjects.length) {
                if (mObjects[i] != null) {
                    clear_count += 1;
                }
            }
        }
        Sys.println(prefix + "Cleared " + clear_count + " objects");
        mArrays = [ ];
        mStrings = [ ];
        mObjects = [ ];
#if cpp
        cpp.vm.Gc.run(true);
#elseif neko
        neko.vm.Gc.run(true);
#end
        this.allocate();
    }

    public function dump(prefix : String)
    {
#if cpp
        // Testing enterGCFreeZone and enable
        cpp.vm.Gc.enable(false);
        cpp.vm.Gc.enterGCFreeZone();
        cpp.vm.Gc.exitGCFreeZone();
#end
        var arrayCount = this.countArrays();
        var stringCount = this.countStrings();
        var objectCount = this.countObjects();

        Sys.println(prefix + "a: " + arrayCount + ", s: " + stringCount +
                    ", o: " + objectCount);

#if cpp
        cpp.vm.Gc.enable(true);
#end
    }

    private function countArrays() : Int
    {
        var ret = 0;
        if (mArrays != null) {
            for (a in mArrays) {
                if (a != null) {
                    ret += 1;
                }
            }
        }
        if (mObjects != null) {
            for (o in mObjects) {
                if (o != null) {
                    ret += o.countArrays();
                }
            }
        }
        return ret;
    }

    private function countStrings() : Int
    {
        var ret = 0;
        if (mStrings != null) {
            for (s in mStrings) {
                if (s != null) {
                    ret += 1;
                }
            }
        }
        if (mObjects != null) {
            for (o in mObjects) {
                if (o != null) {
                    ret += o.countStrings();
                }
            }
        }
        return ret;
    }

    private function countObjects() : Int
    {
        var ret = 0;
        if (mObjects != null) {
            for (o in mObjects) {
                if (o != null) {
                    ret += o.countObjects() + 1;
                }
            }
        }
        return ret;
    }

    private function iterateArray()
    {
        var which = (mArrays.length == 0) ? 0 :
            (mRandom.random() % mArrays.length);

        var set = (mArrays[which] == null) ? 
            true : ((mRandom.random() % 2) == 0);

        var array : Array<Int> = null;

        if (set) {
            array = new Array<Int>();
            var element_count = mRandom.random() % 1000;
            for (i in 0 ... element_count) {
                array.push(0);
            }
        }

        mArrays[which] = array;
    }

    private function iterateString()
    {
        var which = (mStrings.length == 0) ? 0 :
            (mRandom.random() % mStrings.length);

        var set = (mStrings[which] == null) ? 
            true : ((mRandom.random() % 2) == 0);

        var string : String = null;

        if (set) {
            string = new String(gStrings[mRandom.random() % gStrings.length]);
        }

        mStrings[which] = string;
    }

    private function iterateObject()
    {
        var which = (mObjects.length == 0) ? 0 :
            (mRandom.random() % mObjects.length);

        var object : Object = null;

        if (mObjects[which] == null) {
            object = this.createObject();
        }
        else {
            switch (mRandom.random() % 7) {
            case 0:
                object = null;
                
            case 1:
                object = this.createObject();
                
            default:
                mObjects[which].iterate();
                return;
            }
        }

        mObjects[which] = object;
    }

    private function createObject() : Object
    {
        return new Object(mRandom, Std.int(mMaxArrays / 2),
                          Std.int(mMaxStrings / 2), Std.int(mMaxObjects / 2));
    }

    private function allocate()
    {
        mIterators = new Array<Dynamic>();

        var arrays : Array<Array<Int>> = null;
        var strings : Array<String> = null;
        var objects : Array<Object> = null;

        var arrayCount =
            (mMaxArrays > 0) ? (mRandom.random() % mMaxArrays) : 0;
        if (arrayCount > 0) {
            arrays = new Array<Array<Int>>();
            for (i in 0 ... arrayCount) {
                arrays.push(null);
            }
            mIterators.push(iterateArray);
        }

        var stringCount = 
            (mMaxStrings > 0) ? (mRandom.random() % mMaxStrings) : 0;
        if (stringCount > 0) {
            strings = new Array<String>();
            for (i in 0 ... stringCount) {
                strings.push(null);
            }
            mIterators.push(iterateString);
        }

        var objectCount = 
            (mMaxObjects > 0) ? (mRandom.random() % mMaxObjects) : 0;
        if (objectCount > 0) {
            objects = new Array<Object>();
            for (i in 0 ... objectCount) {
                objects.push(null);
            }
            mIterators.push(iterateObject);
        }

        mArrays = arrays;
        mStrings = strings;
        mObjects = objects;
    }

    private var mRandom : Random;
    private var mIterators : Array<Dynamic>;
    private var mArrays : Array<Array<Int>>;
    private var mStrings : Array<String>;
    private var mObjects : Array<Object>;
    private var mMaxArrays : Int;
    private var mMaxStrings : Int;
    private var mMaxObjects : Int;

    private static var gStrings = [ "", "1", "12", "123", "1234", "12345",
                                    "123456", "1234567", "12345678",
                                    "123456789", "1234567890" ];
}


class Random
{
    public function new(seed : Int)
    {
        this.seed(seed);
    }

    public function random() : Int
    {
        // What are these values? I don't know -- they were in the sample code
        // from wikipedia.
        var a : Int = 18782;
        var r : Int = 0xfffffffe;
        var t : Int;
        var x : Int;
        
        mRotation = (mRotation + 1) & (RESIDUES - 1);
        t = a * mQ[mRotation] + mC;
        mC = (t >> 32);
        x = t + mC;
        if (x < mC) {
            x++;
            mC++;
        }
        mQ[mRotation] = r - x;

        return (mQ[mRotation] < 0) ? -mQ[mRotation] : mQ[mRotation];
    }
    
    private function seed(seed : Int)
    {
        mQ = new Array<Int>();
        
        mQ.push(seed);
        mQ.push(seed + PHI);
        mQ.push(seed + PHI + PHI);
        
        for (i in 3 ... RESIDUES)
        {
            mQ.push(mQ[i - 3] ^ mQ[i - 2] ^ PHI ^ i);
        }
        
        mRotation = RESIDUES - 1;
    }

    // This is the number of pregenerated starting points that are rotated
    // through
    private static inline var RESIDUES : Int = 4096;

    // I don't know what these next two numbers are. They are from the sample
    // code on Wikipedia. If you want to sort through the formulas there, you
    // can figure it out.
    private static inline var PHI : Int = 0x9e3779b9;

    private var mC : Int = 362436;

    // This is the current index of the pregenerated starting point
    private var mRotation : Int;
        
    // This is the array of pregenerated starting points.
    private var mQ : Array<Int>;
}
```

When run with the newest version of hxcpp, it demonstrates that the GC is allowing memory to leak.

When run like so:

```
StressGC -i 10000000 -s 0
```

I see memory usage of the program start out at around 35 MB, and grow continuously as the program runs, to a maximum memory usage of nearly 60 MB by the time it completes.

As a comparison, the hxcpp garbage collector that we use at TiVo, that we wrote ourselves, stays around 29 - 31 MB continuously over the same run, never growing in size beyond that.

For what it's worth, the TiVo garbage collector is still faster than the hxcpp garbage collector for single threaded workloads, although not by much (48.5s for the TiVo GC versus 51.2s for the stock GC).  Its implementation is also vastly simpler.  Another drawback of the stock GC is that it uses over a minute of CPU time due to its multithreaded nature in order to finish the test in 51.2 seconds, so it's burning alot more CPU than the TiVo GC, which is single threaded and takes 48.5 seconds of total CPU time.

The TiVo GC used to be tons faster than the stock GC on multithreaded workloads, but is now about 50% as fast as the stock GC, so that's an area that we could work on in the TiVo GC if we want to achieve parity or better in all respects when compared to the stock GC.

**Comment by bjitivo** [comment]
By the way, I'm measuring resident memory on Linux when I run these tests, not virtual memory.  The virtual memory usage of the stock hxcpp GC is about 50 MB higher than the resident set size.  The TiVo GC runs at about 12 MB more virtual memory than resident set size.

Also, when run like so:

```
StressGC -s 0
```

The stress test runs indefinitely.  With the stock hxcpp GC, it's now at about 150 MB of resident size (200 MB of virtual size) after 50,000,000 iterations.  It just keeps growing.

**Comment by bjitivo** [comment]
At 130,000,000 iterations it's at 300+ MB resident, 350+ MB virtual.  It's definitely leaking.

**Comment by hughsando** [comment]
I am not seeing any leaking here on my windows box.
I have added "SHOW_FRAGMENTATION" define in Immix.cpp, which should show
stats on the allocations, which might help pinpoint the problem.
Leaking in GC is generally to do with fragmentation - but this really
requires at least some long-term storage so I don't think this is the case
here.  I have also experimented with "HXCPP_GC_MOVING" define to allow
defragmentation, but this does not seem to get triggered.  The only other
thing I can think of, is the "large allocations", which fallback to malloc,
which might be getting fragmented under the hood. - But  I think I recall
that tivo did this too?
I note also that the stress test always explicitly runs a full collection.
This is a legitimate use case, although I'm not sure how representative it
is.

I am evolving towards a more modular organization where we can hopefully
optimize the various sub-processes independently, and pick-and-choose the
implementation.  For example, the current marking phase is less efficient
because it must deal with the possibility of stack-overflow when marking
(eg, a long linked-list) but also has some multi-threaded characteristics.
There is nothing that about either of these aspects that is tied to immix.

Similar things can probably be said about the other structures -
finalizers/zombies/roots/objectIds etc. where it should be relatively
simple to share almost all of the implementation.  Other things, such as
zeroing the memory in a separate thread, or thread-local allocator vs
global lock and conservative stack capture may or may not apply to
different methods, but it would be still nice to make as much of this
common as possible.

So I am evolving towards a point where we can use a simple #define to swap
implementations  and sub implementations (while being conscious of the fact
that it should always be in a usable state)   - particularly with the tivo
GC in mind.
It is probably a good time to reexamine your code - could you send me
recent copy/link?  I think last time I was missing a thread header.

Another stress benchmark you may be interested in is in the haxe repo,
tests/benchs/mandelbrot.  This code is uses more objects than it should,
but it is an interesting mix of lots of allocation and a reasonably large
array of retained references.

Hugh

**Comment by bjitivo** [comment]
Are you saying you're not seeing any leaking when running this StressGC program on Windows?

I can't imagine what Windows vs. Linux has to do with the leak.  I would expect it to occur on all platforms similarly as the low level memory management is similar.  I just double checked and StressGC clearly grows unbounded on Linux, for whatever reason. 

I also checked on Mac OS X:

- Install haxe 3.2.1 for Mac OS X
- Install hxcpp haxelib via git
- Build StressGC

The result is that StressGC also demonstrates a memory leak on Mac OS X as the application grows over time.  I was able to use the XCode "Instruments" program to analyze the memory usage of StressGC on Mac OS X and interestingly, the unbounded growth is in 256 byte allocations.  Allocations in all other sizes fluctuated between reasonable bounds, but the 256 byte allocations grew unbounded.  Hope that helps.

**Comment by bjitivo** [comment]
Did you mention the fact that StressGC forces full GCs because of the performance implications?  If so, note that I tried #if 0'ing out all of the forced GCs from StressGC, and the result for StressGC -i 10000000 - s 0 was:

TiVo GC:
real    0m46.338s
user    0m45.869s
sys     0m0.376s

Stock haxe GC:
real    0m49.602s
user    0m56.293s
sys     0m0.368s

Stock GC is still slower, and by a wider margin.

However, as pointed out before, once multithreading comes into play, the stock haxe GC is much faster than the TiVo GC, probably partially or mostly because the TiVo GC doesn't use per-thread allocation pools, which is something that I should probably improve.  I don't think that the slight performance advantage of the TiVo GC in the single threaded case outweighs its much worse performance in the multithreaded case.

**Comment by bjitivo** [comment]
Oh yeah and Mandelbrot -- it's faster on stock haxe GC, and by a pretty significant margin.

If stock haxe GC can be fixed to not leak memory, I think we should probably just go with it, because it is much faster now than it used to be and there appear to be no significant advantages to the TiVo GC anymore.

**Comment by hughsando** [comment]
The leak shows up quite clearly on mac - it appears to be the MarkChunks,
which are separate from the GC memory - should be easy enough to fix.

The Mandelbrot and StressGC are a bit different in one key way - the
Mandelbrot allocates mostly with objects, while StressGC mostly uses
array.  The object code is largely inlined which suggests 2 optimizations -
inline the array code a bit too, and inline the free-list allocator for
speedups on both systems.

Some other optimizations come to mind as well, by making the array resize
code algorithm aware.  Since this code has some latitude is deciding how
much to oversize an array when items are pushed, it should probably use the
free-list size block for the tivo method and round up to the nearest full
line the immix method.

As you say, the gap is much smaller now, but I still have some interest in
a free-list based method.  Perhaps a bit closer to the immix method with
local allocators and inlining the common path, but with a simpler marking
and sweeping.

As an aside, I have also started incude/hx/Unordered.h and hope to increase
the number of platforms where we can use c++11, or maybe add a tr1 option
too.

**Comment by thomasuster** [comment]
Is it possible to craft a test using memUsage or some other memory query method I don't know of to detect if GC leaks? I think I've tried this in the past, but don't remember having much success. Maybe things are different now.

**Comment by hughsando** [comment]
This should be fixed now.
It was not actually a "GC" leak in the sense that it would have shown up in the GC memUsage.
However, it would have shown up in the process memUsage (like other things, such as texture memory) so it would be worth trying to monitor this too if possible.

**Comment by bjitivo** [comment]
I can confirm that commit 5ea050c fixed this issue.  I no longer see the memory leak in the test case I was using to reproduce it.  Feel free to close this issue anytime.  Thank you!

**Comment by tanis2000** [comment]
The latest release 3.2.180 still shows this issue both on my Mac box and on iOS. Has this patch been released already or am I doing something wrong?
Cheers!

**Comment by thomasuster** [comment]
You could try latest build.

Go to http://nmehost.com/hxcpp/

Download hxcpp-3.2.188.zip

```
haxelib install ~/Downloads/hxcpp-3.2.188.zip
```

**Comment by tanis2000** [comment]
I've just tried version 3.2.188 but it's got the same problem.

The code that leaks is the one I posted there:

https://github.com/HaxeFoundation/hxcpp/issues/319#issuecomment-153286448

**Comment by tanis2000** [comment]
I've got some more info through the profiler of XCode. Have a look at those screenshots:

https://dl.dropboxusercontent.com/u/3098924/hxcpp/Instruments2_e_BunnyMarkNez_xcodeproj_e_Posta_in_arrivo__1_148__-_santinelli_altralogica_it_-_Posta_ALTRALOGICA.png

https://dl.dropboxusercontent.com/u/3098924/hxcpp/Instruments2_e_hxcpp_garbage_collector_leaks_memory_%C2%B7_Issue__315_%C2%B7_HaxeFoundation_hxcpp.png

**Comment by Tiago-Ling** [comment]
I'm also experiencing what appears to be a memory leak in garbage collection. There are some allocations that happen during my game state that never get collected after it ends. I tried manually calling the gc and i'm setting all possible references (class scope vars) as null but it still retains the memory. I figure this might be related to local scope variables not being collected as they should, but i don't actually know for sure.

HxScout shows that a lot of these allocations are dynamic and arrays - since i'm rendering stuff with drawTriangles there's a lot of local scope array allocations that could possibly be left by this supposed leak.

This is happening on Windows 10 x64 using Haxe 3.2.0, OpenFL 3.3.8 and Lime 2.6.8. I originally created this related issue here: [FlxSpine leaks memory](https://github.com/HaxeFlixel/flixel-addons/issues/208)

**Comment by bjitivo** [comment]
Tiago-Ling: Be aware that the way that the GC works is that it's not perfectly optimal with regards to collections; it has to be conservative and so some objects may be retained longer than necessary, although on average the extra retained objects should be minimal.

As an example, the collector has to assume that any value on the stack that looks like a pointer to an object is a pointer to that object, and holds that object live.  If you have an object that was allocated at 0x13716f30 and you happen to have a data structure on the stack that holds an integer (or byte data of any kind) that happens to be 0x13716f30, then the object will be held live even if no other objects reference it, just because a random value looks like a pointer to it.  This should be rare but can happen.

**Comment by Tiago-Ling** [comment]
bjitivo: Yeah, i know it's not supposed to be perfect, but in my case a player cannot use the game for more than one hour before hitting the 1.5GB - 2GB memory. Around this amount the application starts to display erratic behavior: some graphics aren't rendered and eventually the application crashes. Unfortunately my application has to run 24/7 so i'm between a rock and a hard place right now.

I read in another issue ( [#319](https://github.com/HaxeFoundation/hxcpp/issues/319) ) about using the `HXCPP_GC_MOVING` flag and started testing with it. It appears to solve the problem - the memory consumption is low and there are no spikes. However a thorough test is not possible since the application always crashes on the first level. The crash was supposed to happen only when using 64 bits, but i suppose the default build command uses 32 bits right?

**Comment by hughsando** [comment]
This looks like a classic case of fragmentation, and GC_MOVING should solve
the issue.
But it looks like you have a bug with "implements Dynamic<Dynamic>" and
GC_MOVING.
I will see if I can get a test case together to highlight and fix the issue.

**Comment by Tiago-Ling** [comment]
Thanks Hugh, i removed the `implements Dynamic<Dynamic>` and now it stopped crashing. The leak is reduced, but still not solved completely - i don't if what's left of it is still related to hxcpp or not.

**Comment by hughsando** [comment]
I'm closing this one now.  Please start another issue if you are still having problems.
