### ISSUE TITLE
Can't build for blackberry: The command line is too long

### ISSUE THREAD

**Issue by pozirk** [HaxeFoundation/hxcpp#401]
Happens on Windows with the latest hxcpp, openfl and -Dlegacy.
Worked fine before for older version.
![bb_toolong](https://cloud.githubusercontent.com/assets/1659590/13998962/3f064d0c-f110-11e5-8bbd-455a8348b01f.jpg)
Thank you!

**Comment by hughsando** [comment]
I'm doing this change a bit blind, but it looks like it should fix the issue.  Let me know how it goes (don't forget to recompile hxcpp.n if you are using git verion)

**Comment by pozirk** [comment]
Thanks Hugh!
I'll try and let you know.

**Comment by pozirk** [comment]
Nope, still the same "The command line is too long." for me.

**Comment by hughsando** [comment]
Can you paste the command-line?  Does it have "-fromfile " in it?

**Comment by pozirk** [comment]
What kind of command-line you need? I build with FlashDevelop.
I have this in Project Properties:
`"$(CompilerPath)/haxelib" run lime build "$(OutputFile)" $(TargetBuild) -$(BuildConfig) -Dfdb -Dlegacy`

**Comment by hughsando** [comment]
I was after something like you posted at the top (but maybe text version) - showing what hxcpp is calling- the "Error running ...." bit.

**Comment by pozirk** [comment]
Here is complete output, and it's really too long:
http://pastebin.com/q5k3nDyW

**Comment by hughsando** [comment]
Yes, its a beauty. There is no "-fromfile" directive in there.  Are you
sure you rebuilt hxcpp.n?
I will have an other look. Might have missed something.

**Comment by pozirk** [comment]
Oops, I didn't rebuild hxcpp.n :)

**Comment by pozirk** [comment]
Ok, now I get a different error:
http://pastebin.com/en7Pj8kc

**Comment by hughsando** [comment]
Hmm, from what I see in the docs, blackberry does not support the fromfile attrubute, so not sure what the fromfile directive is doing in the buildscript.  Maybe @jgranick knows?
So back to the drawing board.  I should remove the "fromfile" line from the xml file.  Maybe changing the objdir from "blackberry-7" to "bb7" will give you just enough to the it to work.

**Comment by hughsando** [comment]
I'm not sure even blackberry is supporting blackberry now, so I'm going to close this one.
