### ISSUE TITLE
Comparison array and null

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/hxcpp#404]
On haxe 3.2.1 the following code:
```
class Test {
	public static function main () 	{
		test([1,2,3,4]);
		test();
	}	
	public static function test (array:Array<Int>=null) 	{
		if (array == null)
			trace([]);
		else
			trace(array);
	}
}
```
pass haxe compilation but fails with g++, something about impossible comparison between array and null.
output: http://pastebin.com/k66RE4Sm

On latest haxe dev I get:
```
Error: /home/ibilon/Code/Haxelibs/hxcpp/src/hx/StdLibs.cpp: In function ‘const char* hx::Init()’:
/home/ibilon/Code/Haxelibs/hxcpp/src/hx/StdLibs.cpp:160:14: error: found ‘:’ in nested-name-specifier, expected ‘::’
       catch(e:Dynamic)
              ^
/home/ibilon/Code/Haxelibs/hxcpp/src/hx/StdLibs.cpp:160:13: error: expected type-specifier before ‘e’
       catch(e:Dynamic)
             ^
/home/ibilon/Code/Haxelibs/hxcpp/src/hx/StdLibs.cpp:160:14: error: expected ‘)’ before ‘::’ token
       catch(e:Dynamic)
              ^
/home/ibilon/Code/Haxelibs/hxcpp/src/hx/StdLibs.cpp:160:14: error: expected ‘{’ before ‘::’ token
/home/ibilon/Code/Haxelibs/hxcpp/src/hx/StdLibs.cpp:160:22: error: expected unqualified-id before ‘)’ token
       catch(e:Dynamic)
                      ^
```

**Comment by ncannasse** [comment]
Fixed by #405

**Comment by ibilon** [comment]
It fixes the second part but it still fails on haxe 3.2.1 with things like:
```
Error: ./src/haxe/Resource.cpp: In static member function ‘static haxe::io::Bytes haxe::Resource_obj::getBytes(String)’:
./src/haxe/Resource.cpp:35:20: error: no match for ‘operator==’ (operand types are ‘Array<unsigned char>’ and ‘null’)
  bool tmp = (array == null());  HX_STACK_VAR(tmp,"tmp");
                    ^
./src/haxe/Resource.cpp:35:20: note: candidates are:
In file included from /home/ibilon/Code/Haxelibs/hxcpp/include/hxcpp.h:319:0,
                 from ./src/haxe/Resource.cpp:1:
/home/ibilon/Code/Haxelibs/hxcpp/include/Array.h:916:16: note: bool Array<ELEM_>::operator==(const cpp::VirtualArray&) const [with ELEM_ = unsigned char]
    inline bool operator==(const cpp::VirtualArray &varray) const { return varray==*this; }
                ^
/home/ibilon/Code/Haxelibs/hxcpp/include/Array.h:916:16: note:   no known conversion for argument 1 from ‘null’ to ‘const cpp::VirtualArray&’
In file included from /home/ibilon/Code/Haxelibs/hxcpp/include/hxcpp.h:311:0,
                 from ./src/haxe/Resource.cpp:1:
/home/ibilon/Code/Haxelibs/hxcpp/include/null.h:37:17: note: bool operator==(bool, const null&)
     inline bool operator op (type inLHS, const null &) { return value; }
```

**Comment by james4k** [comment]
This problem seems to have been brought back in commit https://github.com/HaxeFoundation/hxcpp/commit/a2363e78d294aab594a34a783974026d192d37ea after it was fixed in https://github.com/HaxeFoundation/hxcpp/commit/87841687e2964cc3a91166117cbcccbb014a6931.

**Comment by ibilon** [comment]
Retried and the problem was gone for both haxe 3.2.1 and latest haxe/hxcpp.

**Comment by hughsando** [comment]
Yes, this was fixed by https://github.com/HaxeFoundation/hxcpp/commit/fbac7a2a725b510328008e0743705f54ceac4eec I think.
