### ISSUE TITLE
Failing builds with Haxe 3.4 on Linux + Linc libs

### ISSUE THREAD

**Issue by shakesoda** [HaxeFoundation/hxcpp#559]
Hi, I'm working on a project which uses hxcpp + linc libs and updating from haxe 3.2 + hxcpp 3.2.205 to 3.4.x of each breaks build, every library which includes <hxcpp.h> can't find it. (this can be reproduced using just the example code from [linc_sdl](https://github.com/snowkit/linc_sdl) on Ubuntu 16.04.

I worked around it by modifying all the linc_*.h's to use an absolute path for hxcpp.h, but of course that's not a solution.

I originally wanted to investigate this myself, but I'm not sure how one controls include paths and build flags with hxcpp, is it documented somewhere?

**Comment by hughsando** [comment]
This short answer is that you inject a "-I" compile flag into you build.xml, like https://github.com/HaxeFoundation/hxcpp/blob/master/src/hx/libs/zlib/Build.xml#L12
You can use ```${haxelib:hxcpp}``` to get the current path.

But this depends on why you want hxcpp.h.  If it is for a simple type, you may be ok.  But if you are looking to call some of the member functions directly, correctness may depend on the "HXCPP_API_LEVEL" as well as other build flags, which you would need to get right.
There are 2 ways to make this work. 1 is to compile the code that depends on hxcpp.h actually from inside the haxe code - easiest via the class meta @:cppInclude("./mycppcode.cpp") which pulls your custom cpp code directly into the generated code.  This will already have hxcpp.h included.  This would generally involve splitting the code that needs "hxcpp.h" from the code that does not.
2, the other is to set the files group compile "tags" to "haxe,static" like https://github.com/HaxeFoundation/hxcpp/blob/master/toolchain/haxe-target.xml#L122 which will compile the code with the same flags haxe uses.

**Comment by underscorediscovery** [comment]
This sounds strange, the hxcpp path comes from the includes since they end up in the <haxe> group iirc, I can take a closer look but I have had no trouble running the latest haxe against all the libs since stable 3.4 release and latest hxcpp. I didn't change anything with regards to their include paths so the difference seems odd to me.

**Comment by jcward** [comment]
My hxScout build is exploding as well, and it uses linc_dialogs, so I think it could be related. I get literally 1.4M+ lines of output that there are bad characters in `hxcpp.h.gch`: https://hastebin.com/equsajurav.sql

I don't think I've updated my linc_dialogs repo, but I have everything else (Haxe 3.4, hxcpp git, openfl/lime latest haxelib).

**Comment by hughsando** [comment]
I think this one has been fixed:
https://github.com/underscorediscovery/luxe/issues/385

**Comment by jcward** [comment]
I believe these are linc issues at their core, as I only get them on linc projects (hxScout, linc_dialogs/test, etc). And I'm still getting them with Haxe 3.4.2 and hxcpp 3.4.64 (today's latest official releases, I haven't tried nightlies.)

But, at least `-D NO_PRECOMPILED_HEADERS` gets me around the issue, thanks @eliasku for that tip.

**Comment by underscorediscovery** [comment]
I think I've seen it with normal haxe stuff too, but I'm interested in the magic rain dance to get it to work out of the box of course!

**Comment by hughsando** [comment]
I would need to see a log, but here are some hints:
If you put the files in the "haxe" group so they use the haxe defines/flags then it will try to use a precompiled header for hxcpp.
This in turn means it must be able to find hxcpp.h via a `-Iinclude`.  This should normally be ok.
If you use a precompiled hxcpp header, then the first real line of each cpp files needs to be `#include <hxcpp.h>`.

You can avoid some of this pain by meta-including the cpp file directly into the haxe generated code - then you don't actually need to build the cpp yourself.

**Comment by underscorediscovery** [comment]
Here's the simplest example - the xml has the files node, the cpp has the code - https://github.com/snowkit/linc_timestamp/tree/master/linc 

They are in the haxe group, they do find hxcpp.h in -Iinclude, and they do include hxcpp.h as the first line in any cpp that does include it. Maybe that isn't enough?

**Comment by jcward** [comment]
Interesting -- linc_timestamp/test works for me, but [linc_dialogs](https://github.com/snowkit/linc_dialogs/tree/master/linc)/test does not. Seems like the include is at the top. Is the "haxe" group correct?

**Comment by underscorediscovery** [comment]
It always worked before and it should be compiled with the haxe cpp. It could also get it's own files in the haxe target node? which is better @hughsando

**Comment by hughsando** [comment]
The linc_dialogs just worked for me (windows).
A log with HXCPP_VERBOSE would help.

**Comment by jcward** [comment]
@hughsando - it fails pretty quickly. The `hxcpp.h` file it's missing doesn't exist, but there is an `hxcpp.h.gch` file there.

Here I clean my compiler cache and the output dir before building: https://hastebin.com/mikomazonu.bash

Happy to try / provide anything else that may help.

**Comment by hughsando** [comment]
Ok, looks like a linux thing.
Seems odd it says it can't find /home/jward/hxcpp_cc/haxe/pch0e6e561b/hxcpp.h but the gch is there.

Actually - I think what is going on is that hxcpp.h is getting included twice.  Once in Test.cpp - this is first and uses the pch - all good.  Then from linc_dialogs.h.  This is normally ok, since hxcpp has "#ifndef HXCPP_H" at the top but with pch, this is confusing gcc.

So I think the fix is the surround the "include hxcpp.h" in linc_dialogs.h with 
```c++
#ifndef HXCPP_H
  #include <hxcpp.h>
#endif
```
Or depending on how its supposed to be used, maybe drop the include altogether:
```c++
#ifdef HXCPP_H
  #error "Please include <hxcpp.h> from your c++ file before including this file"
#endif
```
Like in https://github.com/HaxeFoundation/hxcpp/blob/master/include/hx/Object.h

**Comment by jcward** [comment]
The `ifndef` does resolve the problem for me. And the `linc_timestamp.h` (which I didn't have a problem with) file doesn't reference `hxcpp.h` or the hx namespace.

It is weird that including `hxcpp.h` twice causes a problem, and not using precompiled headers fixes it. Maybe it's a bug in `g++ (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4`

**Comment by hughsando** [comment]
Without pch, the hxcpp file excludes itself with an internal "#ifndef HXCPP_H" and is safe to include multiple times.
The pch uses something like "When you see hxcpp.h, substitute these definitions" which is not safe to do multiple times, because the second time should be different, since there are already some other definitions active.
The real problem is the error message - it should be "precompiled header already included", not the "not found" error you got.

**Comment by underscorediscovery** [comment]
hmm, well I'll take a closer look at the call sites and see if I can forward declare anything or see why they were included, and worst case just define it away.
