### ISSUE TITLE
GC_GENERATIONAL causes old object accesses

### ISSUE THREAD

**Issue by RobDangerous** [HaxeFoundation/hxcpp#821]
I'm trying to get generational gc to work and it makes a huge difference but sadly crashes my application after about a minute. In trying to figure out what's going wrong and following your advice from a few months ago I activated HXCPP_GC_CHECK_POINTER - when the generational gc is enabled it's easy to get it to complain about old object accesses.
Here's a simple example I came up with which I tested with Haxe 4rc3 and hxcpp 4.0.19:
```
package;

class Main {
	static var a = new Array<Main>();

	function new() {
		
	}

	public static function main() {
		for (i in 0...10) {
			a.push(new Main());
			trace(a.length);
			cpp.NativeGc.run(true);
		}
	}
}
```
My build.hxml just enables the GC defines:
```
-cp src
-D HXCPP_GC_GENERATIONAL
-D HXCPP_GC_CHECK_POINTER
-main Main
```
Compiling this via `haxe --cpp test --debug build.hxml`, then running it prints
```
src/Main.hx:13: 1
Old object access 029A819C
Called from hxcpp::__hxcpp_main
Called from Main::main Main.hx line 13
Error : Null Object Reference
```

**Comment by hughsando** [comment]
Looks like there was a problem with the check routine.  Good news is that this problem is fixed - bad news is that have not found the real problem.

**Comment by RobDangerous** [comment]
Thanks! Well, next round...

**Comment by RobDangerous** [comment]
In the really big application I still get old object access errors while everything else works fine now. Hope I'll be able to narrow it down somehow.

**Comment by RobDangerous** [comment]
I figured out that I also have to pass HXCPP_GC_GENERATIONAL to the Haxe compiler. That didn't change the behavior for me though apart from generating some C++ compile errors, which I then fixed manually (reported in HaxeFoundation/haxe#8494).
But those _hx_set calls, do I have to do similar things when embedding additional data in Haxe objects using for example @:headerClassCode? #740 didn't turn out very helpful in regarding to what has to be taken care of.

**Comment by hughsando** [comment]
Yes, if you are using native cpp code to set "gc" members in hxcpp objects, then you are going to need to use the setter.  With generational Gc, "old" objects do not always get rescanned.  So if you store a new gc object  in an old object or array, the system needs to know and take some action. it uses
``` cpp
HX_OBJ_WB(this,_hx_v.mPtr)
```
to check this.

For non-gc parents or objects (eg, native objects) you do not need to do anything.
If you are adding your own magical gc objects to a hxcpp object somehow, you are going to need to use the HX_OBJ_WB write barrier macro.

**Comment by RobDangerous** [comment]
Uh oh, I still had this one flying around. Could narrow it down in #851, closing this to minimize my mess.
